answer_question:
  description: >
    Answer medication questions based on medication leaflets.
    Provide the most relevant section from the leaflets and summarize it clearly.

    **Question:**
    {question}

  expected_output: >
    A precise and well-structured response based on the most relevant medication leaflets.
    If applicable, cite the specific section from the leaflets.
    
  agent: pharma_expert
